export class DeepSeekWebError extends Error {
  readonly code: string
  readonly status?: number

  constructor(message: string, code: string, options?: { status?: number; cause?: unknown }) {
    super(message, options?.cause === undefined ? undefined : { cause: options.cause })
    this.name = 'DeepSeekWebError'
    this.code = code
    if (options?.status !== undefined) this.status = options.status
  }
}

export const ERROR_CODES = {
  MISSING_CREDENTIAL: 'MISSING_CREDENTIAL',
  AUTH: 'DEEPSEEK_WEB_AUTH',
  REAUTH_REQUIRED: 'DEEPSEEK_WEB_REAUTH_REQUIRED',
  WAF: 'DEEPSEEK_WEB_WAF',
  RATE_LIMIT: 'DEEPSEEK_WEB_RATE_LIMIT',
  HTTP: 'DEEPSEEK_WEB_HTTP',
  TIMEOUT: 'DEEPSEEK_WEB_TIMEOUT',
  POW: 'DEEPSEEK_WEB_POW',
  POW_UNSUPPORTED: 'DEEPSEEK_WEB_POW_UNSUPPORTED',
  POW_REJECTED: 'DEEPSEEK_WEB_POW_REJECTED',
  PROTOCOL: 'DEEPSEEK_WEB_PROTOCOL',
  PROTOCOL_INCOMPLETE: 'DEEPSEEK_WEB_PROTOCOL_INCOMPLETE',
  TOOL_PROTOCOL: 'DEEPSEEK_WEB_TOOL_PROTOCOL',
  REMOTE_SESSION: 'DEEPSEEK_WEB_REMOTE_SESSION',
  BROWSER_NOT_FOUND: 'DEEPSEEK_WEB_BROWSER_NOT_FOUND',
  BROWSER_INSTALL: 'DEEPSEEK_WEB_BROWSER_INSTALL',
  BROWSER_LAUNCH: 'DEEPSEEK_WEB_BROWSER_LAUNCH',
  BROWSER_CDP: 'DEEPSEEK_WEB_BROWSER_CDP',
  BROWSER_LOGIN_CANCELLED: 'DEEPSEEK_WEB_BROWSER_LOGIN_CANCELLED',
  UNSUPPORTED_IMAGE: 'DEEPSEEK_WEB_UNSUPPORTED_IMAGE',
  PROTOCOL_CORE_MISMATCH: 'DEEPSEEK_WEB_PROTOCOL_CORE_MISMATCH',
} as const
