import { ERROR_CODES as COMPAT_ERROR_CODES } from '@dsh-deepseek-web/compat'

export const ERROR_CODES = {
  ...COMPAT_ERROR_CODES,
  REMOTE_SESSION_LIST_FAILED: 'DEEPSEEK_WEB_REMOTE_SESSION_LIST_FAILED',
  REMOTE_SESSION_HISTORY_FAILED: 'DEEPSEEK_WEB_REMOTE_SESSION_HISTORY_FAILED',
  REMOTE_SESSION_NOT_FOUND: 'DEEPSEEK_WEB_REMOTE_SESSION_NOT_FOUND',
  MIRROR_MATERIALIZE_FAILED: 'DEEPSEEK_WEB_MIRROR_MATERIALIZE_FAILED',
  MIRROR_ALREADY_CONFLICTED: 'DEEPSEEK_WEB_MIRROR_ALREADY_CONFLICTED',
  MIRROR_UNAVAILABLE: 'DEEPSEEK_WEB_MIRROR_UNAVAILABLE',
  FORK_SOURCE_NOT_FOUND: 'DEEPSEEK_WEB_FORK_SOURCE_NOT_FOUND',
  FORK_MESSAGE_NOT_FOUND: 'DEEPSEEK_WEB_FORK_MESSAGE_NOT_FOUND',
  FORK_MESSAGE_NOT_DEEPSEEK_WEB: 'DEEPSEEK_WEB_FORK_MESSAGE_NOT_DEEPSEEK_WEB',
  FORK_OPEN_TURN: 'DEEPSEEK_WEB_FORK_OPEN_TURN',
  FORK_WORKSPACE_NOT_FOUND: 'DEEPSEEK_WEB_FORK_WORKSPACE_NOT_FOUND',
  FORK_WORKSPACE_ATTACH_FAILED: 'DEEPSEEK_WEB_FORK_WORKSPACE_ATTACH_FAILED',
  FORK_INCOMPATIBLE_SESSION: 'DEEPSEEK_WEB_FORK_INCOMPATIBLE_SESSION',
} as const

export { COMPAT_ERROR_CODES }

export function asLlmCode(code: string): string {
  if (code === ERROR_CODES.REAUTH_REQUIRED) return 'AUTH'
  if (code === ERROR_CODES.RATE_LIMIT) return 'RATE_LIMIT'
  if (code === ERROR_CODES.TIMEOUT) return 'TIMEOUT'
  if (code === ERROR_CODES.MISSING_CREDENTIAL) return 'MISSING_CREDENTIAL'
  return code
}
